stages:
  - build
  - deploy

build:
  stage: build
  image: public.ecr.aws/h2u7f9u5/awscli:latest
  script:
    - yarn
    - yarn run build
    - yarn run export
  artifacts:
    name: 'publish'
    paths:
      - out
  rules:
    - if: $CI_COMMIT_TAG

deploy:
  stage: deploy
  image: public.ecr.aws/h2u7f9u5/awscli:latest
  dependencies:
    - build
  script:
    - cd out/
    - aws s3 sync ./ s3://$BUCKET_NAME/$CI_COMMIT_TAG --delete --cache-control "max-age=3153600"
  only:
    - tags
  except:
    - /^release\/.*$/
