version: '2'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: manufatto-front:latest
    stdin_open: true
    container_name: manufatto-front
    command: bash -c 'yarn && yarn dev'
    volumes:
      - ./:/tmp/frontend-build
      - ./node_modules:/tmp/frontend-build/node_modules:cached
    working_dir: /tmp/frontend-build
    ports:
      - 80:3000
