version: '2'

services:
  front:
    build: .
    image: manufatto-front:latest
    working_dir: /code
    stdin_open: true
    container_name: manufatto-front
    command: bash -c 'yarn && yarn dev'
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules:cached
    ports:
      - 80:3000
